/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kelompok_6;


/**
 *
 * @author achmad_khusnul_yakin
 */
public class frame_Beranda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_Beranda.class.getName());

    /**
     * Creates new form frame_Beranda
     */
    public frame_Beranda() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel_Yakin = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        panel_Yakin1 = new javax.swing.JPanel();
        jToggleButton5 = new javax.swing.JToggleButton();
        panel_Yakin2 = new javax.swing.JPanel();
        jToggleButton4 = new javax.swing.JToggleButton();
        panel_Yakin3 = new javax.swing.JPanel();
        jToggleButton3 = new javax.swing.JToggleButton();
        panel_Yakin4 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        panel_Yakin5 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        panel_Content = new javax.swing.JPanel();
        panel_Atas = new javax.swing.JPanel();
        panel_Bio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_Icon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_Bawah = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda");
        setMinimumSize(new java.awt.Dimension(1000, 377));

        panel_Sidebar.setBackground(java.awt.Color.blue);
        panel_Sidebar.setPreferredSize(new java.awt.Dimension(300, 600));
        panel_Sidebar.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(java.awt.Color.blue);
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 150));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Logo/Logo N.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Kelompok 6 [PBO]");
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        panel_Sidebar.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(java.awt.Color.blue);
        jPanel2.setLayout(new java.awt.GridLayout(6, 1));

        panel_Yakin.setLayout(new java.awt.BorderLayout());

        jToggleButton6.setBackground(java.awt.Color.blue);
        jToggleButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton6.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        jToggleButton6.setText("Biodata Aditya");
        jToggleButton6.addActionListener(this::jToggleButton6ActionPerformed);
        panel_Yakin.add(jToggleButton6, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin);

        panel_Yakin1.setLayout(new java.awt.BorderLayout());

        jToggleButton5.setBackground(java.awt.Color.blue);
        jToggleButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        jToggleButton5.setText("Biodata Audi");
        jToggleButton5.addActionListener(this::jToggleButton5ActionPerformed);
        panel_Yakin1.add(jToggleButton5, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin1);

        panel_Yakin2.setLayout(new java.awt.BorderLayout());

        jToggleButton4.setBackground(java.awt.Color.blue);
        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        jToggleButton4.setText("Biodata Shofi");
        jToggleButton4.addActionListener(this::jToggleButton4ActionPerformed);
        panel_Yakin2.add(jToggleButton4, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin2);

        panel_Yakin3.setLayout(new java.awt.BorderLayout());

        jToggleButton3.setBackground(java.awt.Color.blue);
        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        jToggleButton3.setText("Biodata Khabib");
        jToggleButton3.addActionListener(this::jToggleButton3ActionPerformed);
        panel_Yakin3.add(jToggleButton3, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin3);

        panel_Yakin4.setLayout(new java.awt.BorderLayout());

        jToggleButton2.setBackground(java.awt.Color.blue);
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Logo/icons8-profile-30.png"))); // NOI18N
        jToggleButton2.setText("Biodata Reza");
        jToggleButton2.addActionListener(this::jToggleButton2ActionPerformed);
        panel_Yakin4.add(jToggleButton2, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin4);

        panel_Yakin5.setLayout(new java.awt.BorderLayout());

        jToggleButton1.setBackground(java.awt.Color.blue);
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-profile-30.png"))); // NOI18N
        jToggleButton1.setText("Biodata Yakin");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);
        panel_Yakin5.add(jToggleButton1, java.awt.BorderLayout.CENTER);

        jPanel2.add(panel_Yakin5);

        panel_Sidebar.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_Sidebar, java.awt.BorderLayout.WEST);

        panel_Content.setLayout(new java.awt.BorderLayout());

        panel_Atas.setBackground(new java.awt.Color(255, 255, 255));
        panel_Atas.setLayout(new java.awt.BorderLayout());

        panel_Bio.setBackground(new java.awt.Color(255, 255, 255));
        panel_Bio.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25));
        panel_Bio.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("BIODATA MAHASISWA");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        panel_Bio.add(jLabel1, java.awt.BorderLayout.LINE_START);

        panel_Atas.add(panel_Bio, java.awt.BorderLayout.LINE_START);

        panel_Icon.setBackground(new java.awt.Color(255, 255, 255));
        panel_Icon.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25));
        panel_Icon.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelompok_6/Icon/icons8-exit-35.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 20));
        panel_Icon.add(jLabel2, java.awt.BorderLayout.LINE_END);

        panel_Atas.add(panel_Icon, java.awt.BorderLayout.CENTER);

        panel_Content.add(panel_Atas, java.awt.BorderLayout.PAGE_START);

        panel_Bawah.setBackground(new java.awt.Color(255, 255, 255));
        panel_Bawah.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panel_Bawah.setLayout(new java.awt.CardLayout());
        panel_Content.add(panel_Bawah, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_Content, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frame_Beranda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JPanel panel_Atas;
    private javax.swing.JPanel panel_Bawah;
    private javax.swing.JPanel panel_Bio;
    private javax.swing.JPanel panel_Content;
    private javax.swing.JPanel panel_Icon;
    private javax.swing.JPanel panel_Sidebar;
    private javax.swing.JPanel panel_Yakin;
    private javax.swing.JPanel panel_Yakin1;
    private javax.swing.JPanel panel_Yakin2;
    private javax.swing.JPanel panel_Yakin3;
    private javax.swing.JPanel panel_Yakin4;
    private javax.swing.JPanel panel_Yakin5;
    // End of variables declaration//GEN-END:variables
}
